### VStar Tables

We are now going to combine the all of the tables that we gathered of RRLyrae, Cephied, and LPV stars located in Fornax into a centralized table to utilize for validation of our methods and period/magnitude/distance analysis with light curves. We will clean and filter out bad values and non-relevant columns as well, and check for duplicates and overlapping detections in each list.


Columns of Interest From Each Table:
1. Sky Coordinates: right ascension (deg), declination(deg)
2. Periods (if known), NaN if not
3. E(B-V) --> reddening?
4. Flux Magnitudes (V/I bands, deviations)
5. Amplitudes
6. Classification of variable star (e.g. isCStar for LPV, p2c/anomalous cepheids, not as relevant for rrlyrae)

** For Gaia look into other columns

### Import necessary libraries

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import os
import astroquery.gaia as Gaia

### Data Cleaning / Merging of Variable Star Tables

In [2]:
# retrieve current directory
dir = os.getcwd()
print(dir)

c:\Users\aadib\Coding Stuff\SandquistResearch\VeraRubin\EDA

In [3]:
# retrieve each of tables and convert to pandas dataframes
# Appreviations: bw - Bersier Wood, b - Braga et. al.

bw_rrl_path = os.path.join(dir, 'VStar_Tables', 'RRLyrae_Bersier_Wood.csv')
bw_ceph_path = os.path.join(dir, 'VStar_Tables', 'Cepheid_Bersier_Wood.csv')
bw_lpv_path = os.path.join(dir, 'VStar_Tables', 'LPV_Cand_Bersier_Wood.csv')
b_rrl_path = os.path.join(dir, 'VStar_Tables', 'Braga_RRLyrae.csv')

bw_rrl_df = pd.read_csv(bw_rrl_path)
bw_ceph_df = pd.read_csv(bw_ceph_path)
bw_lpv_df = pd.read_csv(bw_lpv_path)
b_rrl_df = pd.read_csv(b_rrl_path)

# create an empty dataframe for the merged table
v_stars_df = pd.DataFrame()

In [4]:
# look at what each of the tables look like to ensure translated properly
print('Bersier Wood - RR Lyrae\n' + str(bw_rrl_df.head()) + '\n')
print(bw_rrl_df.shape)

Bersier Wood - RR Lyrae
                FBW  o_Vmag    Vmag  e_Vmag  o_Icmag   Icmag  e_Icmag     WS  \
0  J023926.4-344027      28  21.321   0.028       27  20.799    0.042  1.030
1  J023749.8-342427      24  21.389   0.027       24  20.755    0.036  1.422
2  J023750.8-342736      32  21.346   0.021       31  20.744    0.035  2.741
3  J023751.9-342620      32  21.419   0.023       32  20.887    0.033  1.139
4  J023752.8-344615      32  21.469   0.029       32  20.560    0.033  2.005

    Period  E(B-V)      _RA      _DE
0  0.37206   0.025  39.8600 -34.6742
1  0.54365   0.028  39.4575 -34.4075
2  0.58252   0.030  39.4617 -34.4600
3  0.58052   0.029  39.4662 -34.4389
4  0.16459   0.034  39.4700 -34.7708

(515, 12)

In [5]:
print('Bersier Wood - Cepheid\n' + str(bw_ceph_df.head()) + '\n')
print(bw_ceph_df.shape)

Bersier Wood - Cepheid
                FBW    Vmag   V-Ic  e_Vmag  e_V-Ic  E(B-V)       Per Class  \
0  J023803.9-343822  19.478  0.483   0.007   0.012   0.036  15.22830   P2C
1  J023811.9-344023  20.651  1.087   0.015   0.021   0.036   1.21327   P2C
2  J023843.0-344825  19.801  0.558   0.016   0.031   0.031   1.04503    AC
3  J023852.4-343012  19.905  0.602   0.007   0.011   0.027   1.24968    AC
4  J023853.4-343048  19.712  0.564   0.006   0.010   0.027   2.57976   P2C

       _RA      _DE
0  39.5162 -34.6394
1  39.5496 -34.6731
2  39.6792 -34.8069
3  39.7183 -34.5033
4  39.7225 -34.5133

(24, 10)

In [63]:
print('Bersier Wood - LPV\n' + str(bw_lpv_df.head()) + '\n')
print(bw_lpv_df.shape)

Bersier Wood - LPV
                FBW  o_Vmag    Vmag  e_Vmag  o_V-Ic   V-Ic  e_V-Ic  E(B-V)  \
0  J023800.0-344422      32  18.562   0.021      32  1.860   0.026   0.034
1  J023806.1-343119      30  20.233   0.065      30  3.765   0.070   0.033
2  J023812.6-345606      32  18.504   0.022      32  2.291   0.026   0.033
3  J023817.1-342548      32  18.591   0.023      32  2.314   0.030   0.029
4  J023821.3-343618      32  18.335   0.021      32  1.942   0.026   0.034

       OName n_FBW      _RA      _DE
0        NaN   NaN  39.5000 -34.7394
1        NaN   NaN  39.5254 -34.5219
2  DK1, DI30   NaN  39.5525 -34.9350
3   S3, DI13   NaN  39.5712 -34.4300
4        NaN     ?  39.5887 -34.6050

(85, 12)

In [6]:
print('Braga - RR Lyrae\n' + str(b_rrl_df.head()) + '\n')
print(b_rrl_df.shape)

Braga - RR Lyrae
  galaxy     name         ra        dec    vmag  errvmag    bmag  errbmag  \
0      F  A115625  39.564875 -34.840639  21.323    0.026  21.611    0.024
1      F  A117688  39.572042 -34.520583  21.408    0.028  21.646    0.025
2      F  A119208  39.574000 -34.829028  21.341    0.022  21.616    0.023
3      F  A235107  39.768792 -34.116944  21.496    0.028  21.819    0.026
4      F  A241835  39.777833 -34.138028  21.328    0.026  21.618    0.025

     rmag  errrmag  ...  ampb  err_ampb  ampr  err_ampr  ampi  err_ampi  \
0  21.143    0.059  ...  0.76      0.06   NaN       NaN   NaN       NaN
1  21.089    0.048  ...  0.68      0.06  0.64      0.34   NaN       NaN
2  21.215    0.040  ...  0.45      0.04   NaN       NaN   NaN       NaN
3  21.360    0.216  ...  0.38      0.04   NaN       NaN   NaN       NaN
4  21.308    0.046  ...  0.68      0.06   NaN       NaN   NaN       NaN

   ampv_sec  err_ampv_sec  ampb_sec  err_ampb_sec
0       NaN           NaN      0.19          0.03
1       NaN           NaN      0.19          0.02
2       0.2          0.04      0.21          0.03
3       NaN           NaN       NaN           NaN
4       0.3          0.05      0.42          0.04

[5 rows x 27 columns]

(250, 27)

In [7]:
# the braga table has star data from a different galaxy which we don't want
# we only want fornax data
b_rrl_df = b_rrl_df[b_rrl_df['galaxy'] == 'F']

# check this worked
print(b_rrl_df['galaxy'].unique())
b_rrl_df.shape

['F']

(212, 27)

In [8]:
# extract the columns we want which include coordinates, period, flux magnitudes, their errors and any color measurements
# Performed through either choosing or dropping specific columns
bw_rrl_subset = bw_rrl_df[['_RA','_DE', 'Period', 'Vmag', 'e_Vmag', 'Icmag', 'e_Icmag', 'E(B-V)']]
bw_ceph_subset = bw_ceph_df[['_RA','_DE', 'Per', 'Class', 'Vmag', 'e_Vmag', 'V-Ic','e_V-Ic', 'E(B-V)']]
bw_lpv_subset = bw_lpv_df[['_RA', '_DE', 'Vmag', 'e_Vmag', 'V-Ic', 'e_V-Ic', 'E(B-V)']]
b_rrl_subset = b_rrl_df.drop(['galaxy', 'name', 'dominant_mode'], axis=1)

In [9]:
# ensure the tables look as intended
print('Bersier-Wood RR Lyrae ' + str(bw_rrl_subset.shape))
print('Bersier-Wood Cepheid ' + str(bw_ceph_subset.shape))
print('Bersier-Wood LPV ' + str(bw_lpv_subset.shape))
print('Braga et. al. RRLyrae ' + str(b_rrl_subset.shape))

Bersier-Wood RR Lyrae (515, 8)
Bersier-Wood Cepheid (24, 9)
Bersier-Wood LPV (85, 7)
Braga et. al. RRLyrae (212, 24)

In [10]:
# check for any rows with missing values
print(bw_rrl_subset.isnull().sum(), '\n')
print(bw_ceph_subset.isnull().sum(), '\n')
print(bw_lpv_subset.isnull().sum(), '\n')
print(b_rrl_subset.isnull().sum(), '\n') # has some missing values for flux

_RA        0
_DE        0
Period     0
Vmag       0
e_Vmag     0
Icmag      0
e_Icmag    0
E(B-V)     0
dtype: int64

_RA       0
_DE       0
Per       0
Class     0
Vmag      0
e_Vmag    0
V-Ic      0
e_V-Ic    0
E(B-V)    0
dtype: int64

_RA       0
_DE       0
Vmag      0
e_Vmag    0
V-Ic      0
e_V-Ic    0
E(B-V)    0
dtype: int64

ra                0
dec               0
vmag              0
errvmag           0
bmag              0
errbmag           0
rmag              7
errrmag           7
imag              8
errimag           8
per_fo            0
per_fu            7
ampv              0
err_ampv          0
ampb              0
err_ampb          0
ampr            105
err_ampr        105
ampi            154
err_ampi        154
ampv_sec         59
err_ampv_sec     60
ampb_sec         30
err_ampb_sec     30
dtype: int64

In [11]:
# first rename the columns for consistency
bw_rrl_subset = bw_rrl_subset.rename(columns={'_RA': 'ra', '_DE': 'dec', 'Period': 'period'})
bw_ceph_subset = bw_ceph_subset.rename(columns={'_RA': 'ra', '_DE': 'dec', 'Per': 'period', 'Class': 'class'})
bw_lpv_subset = bw_lpv_subset.rename(columns={'_RA': 'ra', '_DE': 'dec'})
b_rrl_subset = b_rrl_subset.rename(columns={'ra': 'ra', 'dec': 'dec', 'per_fu': 'period'})

# create a dict for renaming columns for the braga table
renamed_columns = {'vmag': 'Vmag', 'errvmag': 'e_Vmag', 'errbmag': 'e_bmag', 'errrmag': 'e_rmag', 
                   'errimag': 'e_imag', 'per_fo': 'period_fo', 'per_fu': 'period_fu',
                   'ampv': 'vamp', 'err_ampv': 'e_vamp', 'ampb': 'bamp', 'err_bamp': 'e_bamp',
                   'ampr': 'ramp', 'err_ampr': 'e_ramp', 'ampi': 'iamp', 'err_ampi': 'e_iamp', 
                   'ampv_sec': 'vamp_sec', 'err_ampv_sec': 'e_vamp_sec', 'ampb_sec': 'bamp_sec', 
                   'err_ampb_sec': 'e_bamp_sec'
                }

b_rrl_subset = b_rrl_subset.rename(columns=renamed_columns)

In [12]:
# add columns for the paper / source the data was recieved from
bw_rrl_subset['source'] = 'Bersier Wood'
bw_ceph_subset['source'] = 'Bersier Wood'
bw_lpv_subset['source'] = 'Bersier Wood'
b_rrl_subset['source'] = 'Braga'

# add column for 'main category' representing classification of variable star
bw_rrl_subset['main category'] = 'RRLyrae'
bw_ceph_subset['main category'] = 'Cepheid'
bw_lpv_subset['main category'] = 'LPV'
b_rrl_subset['main category'] = 'RRLyrae'

In [13]:
v_stars_df = pd.concat([bw_rrl_subset, bw_ceph_subset, bw_lpv_subset, b_rrl_subset], ignore_index=True)

In [14]:
v_stars_df

,ra,dec,period,Vmag,e_Vmag,Icmag,e_Icmag,E(B-V),source,main category,...,bamp,err_ampb,ramp,e_ramp,iamp,e_iamp,vamp_sec,e_vamp_sec,bamp_sec,e_bamp_sec
0,39.860000,-34.674200,0.372060,21.321,0.028,20.799,0.042,0.025,Bersier Wood,RRLyrae,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,39.457500,-34.407500,0.543650,21.389,0.027,20.755,0.036,0.028,Bersier Wood,RRLyrae,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,39.461700,-34.460000,0.582520,21.346,0.021,20.744,0.035,0.030,Bersier Wood,RRLyrae,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,39.466200,-34.438900,0.580520,21.419,0.023,20.887,0.033,0.029,Bersier Wood,RRLyrae,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,39.470000,-34.770800,0.164590,21.469,0.029,20.560,0.033,0.034,Bersier Wood,RRLyrae,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
831,40.057292,-34.631472,NaN,21.461,0.059,NaN,NaN,NaN,Braga,RRLyrae,...,0.54,0.04,0.42,0.07,0.32,0.12,NaN,NaN,NaN,NaN
832,40.140875,-34.632778,0.385062,21.327,0.050,NaN,NaN,NaN,Braga,RRLyrae,...,0.56,0.04,NaN,NaN,NaN,NaN,NaN,NaN,0.33,0.03
833,40.141333,-34.592806,0.491461,21.411,0.068,NaN,NaN,NaN,Braga,RRLyrae,...,0.33,0.04,NaN,NaN,NaN,NaN,0.27,0.06,0.29,0.04
834,40.146500,-34.374444,0.548637,21.246,0.060,NaN,NaN,NaN,Braga,RRLyrae,...,0.51,0.03,NaN,NaN,0.44,0.08,0.17,0.06,0.22,0.03
835,40.209208,-34.726500,0.706014,20.810,0.030,NaN,NaN,NaN,Braga,RRLyrae,...,0.43,0.03,0.46,0.10,NaN,NaN,0.14,0.03,0.20,0.02

In [15]:
# lets combine this table with the Gaia data
# get paths
gaia_lpv_path = os.path.join(dir, 'VStar_Tables', 'Gaia_lpv.csv')
gaia_rrl_path = os.path.join(dir, 'VStar_Tables', 'Gaia_rrl.csv')

# convert from csv to pd dataframe
gaia_lpv_df = pd.read_csv(gaia_lpv_path)
gaia_rrl_df = pd.read_csv(gaia_rrl_path)

print(gaia_lpv_df.head(), '\n')
print(gaia_rrl_df.head())

             source_id  frequency  amplitude  is_cstar         ra        dec  \
0  5050073265907250176   0.002906   0.050271     False  39.947134 -35.222809
1  5050083230231341312   0.010379   0.082466      True  40.059224 -34.974525
2  5062109413539821824        NaN        NaN     False  39.731094 -34.821300
3  5062111195948838528        NaN        NaN      True  39.737484 -34.776124
4  5062153290925777792   0.004193   0.312630      True  39.372111 -34.827279

      bp_rp  phot_g_mean_mag  phot_bp_mean_mag  phot_rp_mean_mag
0  1.844376        13.978968         14.888110         13.043735
1  2.026699        16.630085         17.648991         15.622292
2  2.264542        16.787117         17.980379         15.715837
3  3.027506        17.998543         19.775740         16.748234
4  2.471912        17.736242         19.065224         16.593311

             source_id        pf  int_average_g  int_average_bp  \
0  5062159402661953024  0.965480      20.125057       20.188068
1  5062106694822930048  0.487153      20.365597       20.371313
2  5062264513399315584  0.662974      20.526722             NaN
3  5062257847614773376       NaN      20.605513       20.311359
4  5062264406022337280       NaN      20.801468       20.643545

   int_average_rp         ra        dec  parallax     bp_rp
0       19.436100  39.359149 -34.686645 -0.298585  0.729395
1       20.080391  39.530225 -34.856437 -0.133249  0.261129
2             NaN  39.745950 -34.335702 -2.427974  0.896284
3       19.304525  39.775069 -34.500534 -3.115739  0.993624
4       20.033247  39.809513 -34.323897 -1.001526  0.559196

In [16]:
gaia_rrl_df = gaia_rrl_df.rename(columns={'pf': 'period', 'int_average_bp': 'bpmag', 'int_average_g':'gmag', 
                                          'int_average_rp': 'rpmag', 'bp_rp':'bp-rp'})

# create a new column in gaia lpv for period, calculated by taking inverse of frequency
gaia_lpv_df['period'] = 1 / gaia_lpv_df['frequency']
gaia_lpv_df['class'] = gaia_lpv_df['is_cstar'].apply(lambda x: 'CStar' if x == True else 'O-rich Star')

gaia_lpv_df = gaia_lpv_df.rename(columns={'bp_rp': 'bp-rp', 'phot_g_mean_mag': 'gmag', 'phot_bp_mean_mag': 'bpmag', 'phot_rp_mean_mag': 'rpmag'})

In [17]:
gaia_lpv_df['period']

0     344.066999
1      96.346748
2            NaN
3            NaN
4     238.496743
5     217.220779
6            NaN
7            NaN
8     240.785920
9     235.312169
10           NaN
11           NaN
12           NaN
13           NaN
14           NaN
15           NaN
16           NaN
17           NaN
18           NaN
19           NaN
20           NaN
21           NaN
22    154.138422
23           NaN
24           NaN
25           NaN
26           NaN
27           NaN
28           NaN
29    242.898772
30    293.679400
31    620.471251
32    348.384470
33    171.477546
34    260.364308
35           NaN
36           NaN
37    635.963882
38    416.436655
39           NaN
40           NaN
41           NaN
42           NaN
43           NaN
44           NaN
45    243.829816
46    203.290829
47    163.279808
48    541.661598
Name: period, dtype: float64

In [18]:
gaia_lpv_df['class']

0     O-rich Star
1           CStar
2     O-rich Star
3           CStar
4           CStar
5           CStar
6     O-rich Star
7           CStar
8           CStar
9           CStar
10    O-rich Star
11          CStar
12          CStar
13          CStar
14          CStar
15          CStar
16    O-rich Star
17          CStar
18          CStar
19          CStar
20    O-rich Star
21    O-rich Star
22    O-rich Star
23    O-rich Star
24          CStar
25          CStar
26    O-rich Star
27          CStar
28          CStar
29          CStar
30          CStar
31    O-rich Star
32    O-rich Star
33    O-rich Star
34          CStar
35    O-rich Star
36          CStar
37    O-rich Star
38          CStar
39          CStar
40          CStar
41          CStar
42    O-rich Star
43    O-rich Star
44    O-rich Star
45    O-rich Star
46          CStar
47          CStar
48    O-rich Star
Name: class, dtype: object

In [19]:
# get subsets of interest, including coordinates, period, flux magnitudes, and color
gaia_rrl_subset = gaia_rrl_df[['ra', 'dec', 'period', 'gmag', 'bpmag', 'rpmag', 'bp-rp']]
gaia_lpv_subset = gaia_lpv_df[['ra', 'dec', 'period', 'class', 'gmag', 'bpmag', 'rpmag', 'bp-rp']]

In [20]:
# create columns for source and main category of star
gaia_rrl_subset['source'] = 'Gaia'
gaia_lpv_subset['source'] = 'Gaia'

gaia_rrl_subset['main category'] = 'RRLyrae'
gaia_lpv_subset['main category'] = 'LPV'

C:\Users\aadib\AppData\Local\Temp\ipykernel_33824\1373740123.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  gaia_rrl_subset['source'] = 'Gaia'
C:\Users\aadib\AppData\Local\Temp\ipykernel_33824\1373740123.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  gaia_lpv_subset['source'] = 'Gaia'
C:\Users\aadib\AppData\Local\Temp\ipykernel_33824\1373740123.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  gaia_lpv_subset['main category'] = 'LPV'

In [21]:
print(gaia_lpv_subset.head())
print(gaia_lpv_subset.shape)

          ra        dec      period        class       gmag      bpmag  \
0  39.947134 -35.222809  344.066999  O-rich Star  13.978968  14.888110
1  40.059224 -34.974525   96.346748        CStar  16.630085  17.648991
2  39.731094 -34.821300         NaN  O-rich Star  16.787117  17.980379
3  39.737484 -34.776124         NaN        CStar  17.998543  19.775740
4  39.372111 -34.827279  238.496743        CStar  17.736242  19.065224

       rpmag     bp-rp source main category
0  13.043735  1.844376   Gaia           LPV
1  15.622292  2.026699   Gaia           LPV
2  15.715837  2.264542   Gaia           LPV
3  16.748234  3.027506   Gaia           LPV
4  16.593311  2.471912   Gaia           LPV
(49, 10)

In [22]:
print(gaia_rrl_subset.head())
print(gaia_rrl_subset.shape)

          ra        dec    period       gmag      bpmag      rpmag     bp-rp  \
0  39.359149 -34.686645  0.965480  20.125057  20.188068  19.436100  0.729395
1  39.530225 -34.856437  0.487153  20.365597  20.371313  20.080391  0.261129
2  39.745950 -34.335702  0.662974  20.526722        NaN        NaN  0.896284
3  39.775069 -34.500534       NaN  20.605513  20.311359  19.304525  0.993624
4  39.809513 -34.323897       NaN  20.801468  20.643545  20.033247  0.559196

  source main category
0   Gaia       RRLyrae
1   Gaia       RRLyrae
2   Gaia       RRLyrae
3   Gaia       RRLyrae
4   Gaia       RRLyrae
(14, 9)

In [11]:
# see null values for each
print(gaia_rrl_subset.isnull().sum(), '\n')
print(gaia_lpv_subset.isnull().sum(), '\n') # can see many lpvs have missing periods which is expected

ra               0
dec              0
period           3
gmag             0
bpmag            4
rpmag            4
bp-rp            0
source           0
main category    0
dtype: int64

ra                0
dec               0
period           30
class             0
gmag              0
bpmag             0
rpmag             0
bp-rp             0
source            0
main category     0
dtype: int64

In [23]:
v_stars_df = pd.concat([v_stars_df, gaia_rrl_subset, gaia_lpv_subset], ignore_index=True)

In [24]:
# double checking our class column was translated correctly
v_stars_df['class'].unique()

array([nan, 'P2C', 'AC', 'blue', 'P2C?', 'O-rich Star', 'CStar'],
      dtype=object)

In [25]:
v_stars_df

,ra,dec,period,Vmag,e_Vmag,Icmag,e_Icmag,E(B-V),source,main category,...,iamp,e_iamp,vamp_sec,e_vamp_sec,bamp_sec,e_bamp_sec,gmag,bpmag,rpmag,bp-rp
0,39.860000,-34.674200,0.372060,21.321,0.028,20.799,0.042,0.025,Bersier Wood,RRLyrae,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,39.457500,-34.407500,0.543650,21.389,0.027,20.755,0.036,0.028,Bersier Wood,RRLyrae,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,39.461700,-34.460000,0.582520,21.346,0.021,20.744,0.035,0.030,Bersier Wood,RRLyrae,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,39.466200,-34.438900,0.580520,21.419,0.023,20.887,0.033,0.029,Bersier Wood,RRLyrae,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,39.470000,-34.770800,0.164590,21.469,0.029,20.560,0.033,0.034,Bersier Wood,RRLyrae,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
894,40.441648,-34.291025,NaN,NaN,NaN,NaN,NaN,NaN,Gaia,LPV,...,NaN,NaN,NaN,NaN,NaN,NaN,17.425013,18.622169,16.353251,2.268919
895,40.222196,-34.203659,243.829816,NaN,NaN,NaN,NaN,NaN,Gaia,LPV,...,NaN,NaN,NaN,NaN,NaN,NaN,17.899149,18.981697,16.645916,2.335781
896,39.742913,-34.536605,203.290829,NaN,NaN,NaN,NaN,NaN,Gaia,LPV,...,NaN,NaN,NaN,NaN,NaN,NaN,17.573246,18.800655,16.482256,2.318399
897,39.919195,-34.337461,163.279808,NaN,NaN,NaN,NaN,NaN,Gaia,LPV,...,NaN,NaN,NaN,NaN,NaN,NaN,16.944231,18.394299,15.806978,2.587320
898,40.642356,-33.766035,541.661598,NaN,NaN,NaN,NaN,NaN,Gaia,LPV,...,NaN,NaN,NaN,NaN,NaN,NaN,9.194800,11.784486,7.745113,4.039372

In [28]:
# check for duplicate stars through looking at their 'ra' and 'da'
duplicates = v_stars_df[v_stars_df.duplicated(subset=['ra', 'dec'], keep=False)]
duplicates

,ra,dec,period,Vmag,e_Vmag,Icmag,e_Icmag,E(B-V),source,main category,...,iamp,e_iamp,vamp_sec,e_vamp_sec,bamp_sec,e_bamp_sec,gmag,bpmag,rpmag,bp-rp
162,39.7796,-34.5544,0.33609,20.780,0.017,19.971,0.019,0.026,Bersier Wood,RRLyrae,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
236,39.9383,-34.7206,0.53130,21.206,0.019,20.769,0.031,0.024,Bersier Wood,RRLyrae,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
251,39.9783,-34.6003,0.57469,20.990,0.016,20.506,0.025,0.025,Bersier Wood,RRLyrae,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
264,39.9967,-34.4917,0.52005,21.498,0.024,20.969,0.037,0.021,Bersier Wood,RRLyrae,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
288,40.0567,-34.4564,0.56415,21.451,0.023,21.128,0.037,0.020,Bersier Wood,RRLyrae,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
345,40.2429,-34.7644,0.48111,20.800,0.015,20.059,0.020,0.024,Bersier Wood,RRLyrae,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
389,39.9967,-34.4917,0.52011,25.161,0.009,18.383,0.036,0.021,Bersier Wood,RRLyrae,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
412,40.0567,-34.4564,0.56421,21.461,0.023,21.151,0.037,0.020,Bersier Wood,RRLyrae,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
520,39.7796,-34.5544,0.50812,20.786,0.017,NaN,NaN,0.026,Bersier Wood,Cepheid,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
526,39.9383,-34.7206,1.14259,21.230,0.019,NaN,NaN,0.024,Bersier Wood,Cepheid,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
530,39.9783,-34.6003,0.57442,21.022,0.016,NaN,NaN,0.025,Bersier Wood,Cepheid,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
538,40.2429,-34.7644,0.48106,20.786,0.018,NaN,NaN,0.024,Bersier Wood,Cepheid,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

- Looks like all of the duplicates just show up in the Bersier Wood papers with a lot of the same RRLyrae / Cepheid having the exact same coordinates
- Going to ignore for now until we get some input from Sandquist on it

In [32]:
#Move to csv
output_path = os.path.join(dir, 'v_stars.csv')
v_stars_df.to_csv(output_path, index=False)

In [34]:
v_stars_df.shape

(899, 36)