### In this notebook we will query Gaia DR3's pulsating variable star catalogs specifically for the 7 regions covered by Rubin's DP1
### We will then match these labeled stars to DP1 (by their coordinates) so that we can assign labels to objects with more extensive data capture within DP1

In [1]:
#Imports
from astroquery.gaia import Gaia
from astroquery.vizier import Vizier
from astropy.coordinates import SkyCoord
import astropy.units as u
import csv
import pandas as pd
from lsst.rsp import get_tap_service

from sklearn import svm

In [2]:
#get an instance of the TAP service and assert that it exists

service = get_tap_service("tap")
assert service is not None

**Creating a function so that we can query each region/type with one line**

**We originally attempted to do this with 3 queries (one for each pulsating variable star class), however, we were unable to properly assign region labels through pandas and so this is an approach that we're confident in**

**That being said, it is fairly inefficient so it might be better to look into an approach that uses less queries**

In [4]:
def queryGaia(variable_star_type, region, radius):
    if variable_star_type == 'RRLyrae':
        source = 'gaiadr3.vari_rrlyrae'
    elif variable_star_type == 'Cepheid':
        source = 'gaiadr3.vari_cepheid'
    elif variable_star_type == 'LPV':
       source = 'gaiadr3.vari_long_period_variable'

    # 47 Tuc Globular Cluster | 00h24m05s -72d04m48s | 6.02, -72.08
    # Low Ecliptic Latitude Field | 02h31m26s +06d58m48s | 37.86, 6.98
    # Fornax Dwarf Spheroidal Galaxy | 02h40m00s -34d27m00s | 40.00, -34.4
    # Extended Chandra Deep Field South (ECDFS) | 03h32m31s -28d06m00s | 53.13, -28.10
    # Euclid Deep Field South (EDFS) | 03h56m24s -48d43m48s | 59.10, -48.73
    # Low Galactic Latitude Field | 06h20m00s -25d00m00s | 95.00, -25.00
    # Seagull Nebula | 07h04m55s -10d30m36s | 106.23, -10.51
    if region == '47':
        center_ra = '6.02'
        center_dec = '-72.08'
    elif region == 'LELF':
        center_ra = '37.86'
        center_dec = '6.98'
    elif region == 'Fornax':
        center_ra = '40.00'
        center_dec = '-34.4'
    elif region == 'ECDFS':
        center_ra = '53.13'
        center_dec = '-28.10'
    elif region == 'EDFS':
        center_ra = '59.10'
        center_dec = '-48.73'
    elif region == 'LGLF':
        center_ra = '95.00'
        center_dec = '-25.00'
    elif region == 'Seagull':
        center_ra = '106.23'
        center_dec = '-10.51'

    # print('center_ra: ' + str(center_ra))
    # print('center_dec: ' + str(center_dec))
    
    query = f'''SELECT TOP 1000 s.source_id, g.ra, g.dec
            FROM {source} AS s
            JOIN gaiadr3.gaia_source AS g
            ON s.source_id = g.source_id
            WHERE CONTAINS(POINT('ICRS', ra, dec), CIRCLE('ICRS', {center_ra}, {center_dec}, {radius})) = 1
            '''

    job_gaia = Gaia.launch_job_async(query)
    df_gaia = job_gaia.get_results().to_pandas()
    return df_gaia

**Running the queries**

In [5]:
df_47_rrl = queryGaia('RRLyrae', '47', 1)
df_47_ceph = queryGaia('Cepheid', '47', 1)
df_47_lpv = queryGaia('LPV', '47', 1)

df_LELF_rrl = queryGaia('RRLyrae', 'LELF', 1)
df_LELF_ceph = queryGaia('Cepheid', 'LELF', 1)
df_LELF_lpv = queryGaia('LPV', 'LELF', 1)

df_Fornax_rrl = queryGaia('RRLyrae', 'Fornax', 1)
df_Fornax_ceph = queryGaia('Cepheid', 'Fornax', 1)
df_Fornax_lpv = queryGaia('LPV', 'Fornax', 1)

df_ECDFS_rrl = queryGaia('RRLyrae', 'ECDFS', 1)
df_ECDFS_ceph = queryGaia('Cepheid', 'ECDFS', 1)
df_ECDFS_lpv = queryGaia('LPV', 'ECDFS', 1)

df_EDFS_rrl = queryGaia('RRLyrae', 'EDFS', 1)
df_EDFS_ceph = queryGaia('Cepheid', 'EDFS', 1)
df_EDFS_lpv = queryGaia('LPV', 'EDFS', 1)

df_LGLF_rrl = queryGaia('RRLyrae', 'LGLF', 1)
df_LGLF_ceph = queryGaia('Cepheid', 'LGLF', 1)
df_LGLF_lpv = queryGaia('LPV', 'LGLF', 1)

df_Seagull_rrl = queryGaia('RRLyrae', 'Seagull', 1)
df_Seagull_ceph = queryGaia('Cepheid', 'Seagull', 1)
df_Seagull_lpv = queryGaia('LPV', 'Seagull', 1)

print('All queries FINISHED')

INFO: Query finished. [astroquery.utils.tap.core]

INFO: Query finished. [astroquery.utils.tap.core]

INFO: Query finished. [astroquery.utils.tap.core]

INFO: Query finished. [astroquery.utils.tap.core]

INFO: Query finished. [astroquery.utils.tap.core]

INFO: Query finished. [astroquery.utils.tap.core]

INFO: Query finished. [astroquery.utils.tap.core]

INFO: Query finished. [astroquery.utils.tap.core]

INFO: Query finished. [astroquery.utils.tap.core]

INFO: Query finished. [astroquery.utils.tap.core]

INFO: Query finished. [astroquery.utils.tap.core]

INFO: Query finished. [astroquery.utils.tap.core]

INFO: Query finished. [astroquery.utils.tap.core]

INFO: Query finished. [astroquery.utils.tap.core]

INFO: Query finished. [astroquery.utils.tap.core]

INFO: Query finished. [astroquery.utils.tap.core]

INFO: Query finished. [astroquery.utils.tap.core]

INFO: Query finished. [astroquery.utils.tap.core]

INFO: Query finished. [astroquery.utils.tap.core]

INFO: Query finished. [astroquery.utils.tap.core]

INFO: Query finished. [astroquery.utils.tap.core]

All queries FINISHED

**Assigning region labels so that we can identify where each star came from later on**

In [6]:
df_47_rrl['Region'] = '47'
df_47_ceph['Region'] = '47'
df_47_lpv['Region'] = '47'

df_LELF_rrl['Region'] = 'LELF'
df_LELF_ceph['Region'] = 'LELF'
df_LELF_ceph['Region'] = 'LELF'

df_Fornax_rrl['Region'] = 'Fornax'
df_Fornax_ceph['Region'] = 'Fornax'
df_Fornax_lpv['Region'] = 'Fornax'

df_ECDFS_rrl['Region'] = 'ECDFS'
df_ECDFS_ceph['Region'] = 'ECDFS'
df_ECDFS_lpv['Region'] = 'ECDFS'

df_EDFS_rrl['Region'] = 'EDFS'
df_EDFS_rrl['Region'] = 'EDFS'
df_EDFS_rrl['Region'] = 'EDFS'

df_LGLF_rrl['Region'] = 'LGLF'
df_LGLF_ceph['Region'] = 'LGLF'
df_LGLF_lpv['Region'] = 'LGLF'

df_Seagull_rrl['Region'] = 'Seagull'
df_Seagull_ceph['Region'] = 'Seagull'
df_Seagull_lpv['Region'] = 'Seagull'

In [7]:
print(f'{"Region":<8} | {"RRLyrae":>7} | {"Cepheid":>7} | {"LPV":>5}')
print('-' * 37)
print(f'{"47":<8} | {len(df_47_rrl):>7} | {len(df_47_ceph):>7} | {len(df_47_lpv):>5}')
print(f'{"LELF":<8} | {len(df_LELF_rrl):>7} | {len(df_LELF_ceph):>7} | {len(df_LELF_lpv):>5}')
print(f'{"Fornax":<8} | {len(df_Fornax_rrl):>7} | {len(df_Fornax_ceph):>7} | {len(df_Fornax_lpv):>5}')
print(f'{"ECDFS":<8} | {len(df_ECDFS_rrl):>7} | {len(df_ECDFS_ceph):>7} | {len(df_ECDFS_lpv):>5}')
print(f'{"EDFS":<8} | {len(df_EDFS_rrl):>7} | {len(df_EDFS_ceph):>7} | {len(df_EDFS_lpv):>5}')
print(f'{"LGLF":<8} | {len(df_LGLF_rrl):>7} | {len(df_LGLF_ceph):>7} | {len(df_LGLF_lpv):>5}')
print(f'{"Seagull":<8} | {len(df_Seagull_rrl):>7} | {len(df_Seagull_ceph):>7} | {len(df_Seagull_lpv):>5}')

Region   | RRLyrae | Cepheid |   LPV
-------------------------------------
47       |     305 |      24 |   169
LELF     |       4 |       0 |     0
Fornax   |      19 |       0 |    49
ECDFS    |       2 |       0 |     1
EDFS     |       3 |       0 |     1
LGLF     |       6 |       0 |     4
Seagull  |       3 |       1 |    42

**Combining all stars of the same class (rrl, ceph, lpv) into one dataframe for each class**

In [69]:
df_gaia_rrl = pd.concat([df_47_rrl, df_LELF_rrl, df_Fornax_rrl, df_ECDFS_rrl, df_EDFS_rrl, df_LGLF_rrl, df_Seagull_rrl])
df_gaia_ceph = pd.concat([df_47_ceph, df_LELF_ceph, df_Fornax_ceph, df_ECDFS_ceph, df_EDFS_ceph, df_LGLF_ceph, df_Seagull_ceph])
df_gaia_lpv = pd.concat([df_47_lpv, df_LELF_lpv, df_Fornax_lpv, df_ECDFS_lpv, df_EDFS_lpv, df_LGLF_lpv, df_Seagull_lpv])

**Quering RSP diaObject so that we can match our labeled pulsating variable stars to diaObjects**

In [70]:
#RSP Query
query = """SELECT diaObjectId, ra, dec, g_psfFluxMean, r_psfFluxMean, i_psfFluxMean,
        g_psfFluxSigma, r_psfFluxSigma, i_psfFluxSigma,
        g_psfFluxChi2, r_psfFluxChi2, i_psfFluxChi2,
        g_psfFluxStetsonJ, r_psfFluxStetsonJ, i_psfFluxStetsonJ,
        g_psfFluxMAD, r_psfFluxMAD, i_psfFluxMAD,
        g_psfFluxNdata, r_psfFluxNdata, i_psfFluxNdata, nDiaSources
        FROM dp1.DiaObject
        WHERE ra IS NOT NULL
        AND dec IS NOT NULL
        """

job = service.submit_job(query)
job.run()
job.wait(phases=['COMPLETED', 'ERROR'])
print('Job phase is', job.phase)
if job.phase == 'ERROR':
    job.raise_if_error()
assert job.phase == 'COMPLETED'
df_rsp = job.fetch_result().to_table().to_pandas() #get results -> turn into table -> turn table into pandas dataframe
print(str(len(df_rsp)))

Job phase is COMPLETED
1089818

In [71]:
print((df_rsp.isnull().sum() / len(df_rsp)) * 100)

diaObjectId           0.000000
ra                    0.000000
dec                   0.000000
g_psfFluxMean        66.969898
r_psfFluxMean        53.487738
i_psfFluxMean        82.697478
g_psfFluxSigma       92.416991
r_psfFluxSigma       87.551316
i_psfFluxSigma       92.919368
g_psfFluxChi2        66.969898
r_psfFluxChi2        53.487738
i_psfFluxChi2        82.697478
g_psfFluxStetsonJ    92.416991
r_psfFluxStetsonJ    87.551316
i_psfFluxStetsonJ    92.919368
g_psfFluxMAD         66.969898
r_psfFluxMAD         53.487738
i_psfFluxMAD         82.697478
g_psfFluxNdata       66.969898
r_psfFluxNdata       53.487738
i_psfFluxNdata       82.697478
nDiaSources           0.000000
dtype: float64

In [72]:
df_rsp

,diaObjectId,ra,dec,g_psfFluxMean,r_psfFluxMean,i_psfFluxMean,g_psfFluxSigma,r_psfFluxSigma,i_psfFluxSigma,g_psfFluxChi2,...,g_psfFluxStetsonJ,r_psfFluxStetsonJ,i_psfFluxStetsonJ,g_psfFluxMAD,r_psfFluxMAD,i_psfFluxMAD,g_psfFluxNdata,r_psfFluxNdata,i_psfFluxNdata,nDiaSources
0,579582540692586614,7.273014,-72.588645,NaN,-2521.070801,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,0.000000,NaN,NaN,1.0,NaN,1
1,579582540692586582,7.296048,-72.545473,NaN,-2745.098633,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,0.000000,NaN,NaN,1.0,NaN,1
2,579575325147529895,5.193821,-72.602595,2570.403564,NaN,NaN,NaN,NaN,NaN,0.000000e+00,...,NaN,NaN,NaN,0.0,NaN,NaN,1.0,NaN,NaN,1
3,579575325147529914,5.363321,-72.567318,-1793.288696,NaN,2212.33252,NaN,NaN,NaN,1.313750e-13,...,NaN,NaN,NaN,0.0,NaN,0.0,1.0,NaN,1.0,2
4,579575325147529913,5.450513,-72.567214,-1709.251587,-2655.574951,-1996.10376,NaN,NaN,NaN,1.304240e-13,...,NaN,NaN,NaN,0.0,0.000000,0.0,1.0,1.0,1.0,3
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1089813,630406503613861832,106.575658,-10.321021,NaN,-1750.705811,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,0.000000,NaN,NaN,1.0,NaN,1
1089814,630406503613861831,106.576428,-10.319524,NaN,-1508.708618,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,0.000000,NaN,NaN,1.0,NaN,1
1089815,630406503613861830,106.572809,-10.322930,NaN,-1529.663818,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,0.000000,NaN,NaN,1.0,NaN,1
1089816,630406503613861829,106.639648,-10.219387,-2107.257812,-4189.962402,NaN,NaN,914.848746,NaN,4.698130e-13,...,NaN,1.729173,NaN,0.0,646.895996,NaN,1.0,2.0,NaN,3
1089817,630406503613861828,106.588644,-10.295308,NaN,-1324.357666,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,0.000000,NaN,NaN,1.0,NaN,1

**Matching coordinates**

Any object within 1 arcsecond we are confident enough in that we are considering it a "match"

In [ ]:
#Converting RA/DEC from RSP to SkyCoord Objects
coords_rsp = SkyCoord(ra=df_rsp['ra'].values*u.deg, dec=df_rsp['dec'].values *u.deg)

In [74]:
#Converting RA/DEC from gaia rrl/ceph/lpv to SkyCoord objects
df_gaia_rrl['ra'] = pd.to_numeric(df_gaia_rrl['ra'], errors='coerce')
df_gaia_rrl['dec'] = pd.to_numeric(df_gaia_rrl['dec'], errors='coerce')

df_gaia_ceph['ra'] = pd.to_numeric(df_gaia_ceph['ra'], errors='coerce')
df_gaia_ceph['dec'] = pd.to_numeric(df_gaia_ceph['dec'], errors='coerce')

df_gaia_lpv['ra'] = pd.to_numeric(df_gaia_lpv['ra'], errors='coerce')
df_gaia_lpv['dec'] = pd.to_numeric(df_gaia_lpv['dec'], errors='coerce')

coords_gaia_rrl = SkyCoord(ra=df_gaia_rrl['ra'].values*u.deg, dec=df_gaia_rrl['dec'].values*u.deg)
coords_gaia_ceph = SkyCoord(ra=df_gaia_ceph['ra'].values*u.deg, dec=df_gaia_ceph['dec'].values*u.deg)
coords_gaia_lpv = SkyCoord(ra=df_gaia_lpv['ra'].values*u.deg, dec=df_gaia_lpv['dec'].values*u.deg)

In [87]:
idx_rrl, d2d_rrl, _ = coords_gaia_rrl.match_to_catalog_sky(coords_rsp)
matches_rrl = d2d_rrl < 1* u.arcsec
matched_gaia_rrl = df_gaia_rrl[matches_rrl].reset_index(drop=True)
matched_diaObjects_rrl = df_rsp.iloc[idx_rrl[matches_rrl]].reset_index(drop=True)
matched_diaObjects_rrl['Region'] = matched_gaia_rrl["Region"]

idx_ceph, d2d_ceph, _ = coords_gaia_ceph.match_to_catalog_sky(coords_rsp)
matches_ceph = d2d_ceph < 1* u.arcsec
matched_gaia_ceph = df_gaia_ceph[matches_ceph].reset_index(drop=True)
matched_diaObjects_ceph = df_rsp.iloc[idx_ceph[matches_ceph]].reset_index(drop=True)
matched_diaObjects_ceph['Region'] = matched_gaia_ceph["Region"]

idx_lpv, d2d_lpv, _ = coords_gaia_lpv.match_to_catalog_sky(coords_rsp)
matches_lpv = d2d_lpv < 1* u.arcsec
matched_gaia_lpv = df_gaia_lpv[matches_lpv].reset_index(drop=True)
matched_diaObjects_lpv = df_rsp.iloc[idx_lpv[matches_lpv]].reset_index(drop=True)
matched_diaObjects_lpv['Region'] = matched_gaia_lpv["Region"]

These are the diaObject values for all labeled Gaia stars that we were able to match to Rubin DP1's diaObject catalog

In [88]:
matched_diaObjects_rrl

,diaObjectId,ra,dec,g_psfFluxMean,r_psfFluxMean,i_psfFluxMean,g_psfFluxSigma,r_psfFluxSigma,i_psfFluxSigma,g_psfFluxChi2,...,r_psfFluxStetsonJ,i_psfFluxStetsonJ,g_psfFluxMAD,r_psfFluxMAD,i_psfFluxMAD,g_psfFluxNdata,r_psfFluxNdata,i_psfFluxNdata,nDiaSources,Region
0,579583227887354659,7.277627,-72.453601,NaN,6659.355957,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,0.000000,NaN,NaN,1.0,NaN,1,47
1,579574706672238627,4.974821,-72.683373,2142.085449,NaN,NaN,NaN,NaN,NaN,0.000000e+00,...,NaN,NaN,0.000000,NaN,NaN,1.0,NaN,NaN,1,47
2,579574569233285135,6.011728,-72.654608,-2534.255615,NaN,-7.695698,NaN,NaN,7380.872768,5.176740e-13,...,NaN,15.224242,0.000000,NaN,5219.069824,1.0,NaN,2.0,3,47
3,579575187708576418,6.298868,-72.611684,7049.521484,NaN,2416.182129,NaN,NaN,NaN,0.000000e+00,...,NaN,NaN,0.000000,NaN,0.000000,1.0,NaN,1.0,2,47
4,579575256428052817,5.980350,-72.590526,2554.464600,-6780.240234,-801.362061,NaN,2091.403995,5294.444401,0.000000e+00,...,4.992266,12.702006,0.000000,1478.849976,4499.990234,1.0,2.0,4.0,7,47
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
82,614439120877387848,95.013508,-24.443539,NaN,59789.472656,-198197.656250,NaN,211665.313131,NaN,NaN,...,119.918695,NaN,NaN,104605.000000,0.000000,NaN,4.0,1.0,11,LGLF
83,614436990573609020,95.124193,-25.043283,10664.968750,-103542.789062,115696.320312,236679.172789,217021.149015,169139.897988,1.741140e+06,...,148.705147,109.824706,213721.000000,115552.000000,63010.898438,50.0,55.0,19.0,190,LGLF
84,614438433682620451,94.997243,-24.689513,284696.187500,188277.781250,NaN,620882.486643,561544.600481,NaN,4.948110e+06,...,326.814580,NaN,225749.000000,472285.000000,NaN,35.0,54.0,NaN,151,LGLF
85,614439052157911527,95.266494,-24.538765,227418.609375,161252.781250,164027.968750,412007.915361,248352.363162,NaN,2.178640e+05,...,173.746915,NaN,57696.398438,3015.409912,0.000000,4.0,3.0,1.0,17,LGLF
86,614431011979133047,94.790826,-24.681148,1567.132080,1291.368164,183.626526,7373.947285,6639.214868,5384.510285,2.987890e+04,...,24.457161,13.449594,2969.939941,6310.859863,3541.000000,28.0,33.0,8.0,74,LGLF

In [89]:
matched_diaObjects_rrl['Region'].value_counts()

Region
47        67
Fornax    11
LGLF       5
LELF       3
EDFS       1
Name: count, dtype: int64

In [90]:
matched_diaObjects_ceph

,diaObjectId,ra,dec,g_psfFluxMean,r_psfFluxMean,i_psfFluxMean,g_psfFluxSigma,r_psfFluxSigma,i_psfFluxSigma,g_psfFluxChi2,...,r_psfFluxStetsonJ,i_psfFluxStetsonJ,g_psfFluxMAD,r_psfFluxMAD,i_psfFluxMAD,g_psfFluxNdata,r_psfFluxNdata,i_psfFluxNdata,nDiaSources,Region
0,579582540692586533,7.103005,-72.476959,NaN,-74538.890625,-16331.326172,NaN,283995.259318,NaN,NaN,...,107.648640,NaN,NaN,6715.229980,0.0,NaN,9.0,1.0,10,47
1,579576012342296929,5.474521,-72.373022,-2584.693848,-45243.054688,-57625.726562,125493.267019,94762.097552,78457.27323,237507.0,...,109.712154,82.75554,12320.900391,17794.300781,27993.0,7.0,24.0,12.0,43,47
2,579578623682413547,6.675689,-71.673451,NaN,-87457.179688,-9873.979492,NaN,64972.255225,NaN,NaN,...,86.150786,NaN,NaN,36426.000000,0.0,NaN,4.0,1.0,5,47
3,630406778491766139,105.859294,-10.282883,-107177.359375,NaN,NaN,161462.592668,NaN,NaN,283399.0,...,NaN,NaN,69538.796875,NaN,NaN,5.0,NaN,NaN,5,Seagull

In [91]:
matched_diaObjects_ceph['Region'].value_counts()

Region
47         3
Seagull    1
Name: count, dtype: int64

In [92]:
matched_diaObjects_lpv

,diaObjectId,ra,dec,g_psfFluxMean,r_psfFluxMean,i_psfFluxMean,g_psfFluxSigma,r_psfFluxSigma,i_psfFluxSigma,g_psfFluxChi2,...,r_psfFluxStetsonJ,i_psfFluxStetsonJ,g_psfFluxMAD,r_psfFluxMAD,i_psfFluxMAD,g_psfFluxNdata,r_psfFluxNdata,i_psfFluxNdata,nDiaSources,Region
0,579575187708576287,6.461538,-72.613643,-2874.174316,22179.582031,-18217.445312,NaN,NaN,1513.896284,0.000000,...,NaN,-0.695827,0.000000,0.000000,1070.48999,1.0,1.0,2.0,4,47
1,579582540692586566,7.071711,-72.600880,NaN,-15740.595703,NaN,NaN,35445.346709,NaN,NaN,...,18.939264,NaN,NaN,25063.599609,NaN,NaN,2.0,NaN,2,47
2,579575118989099026,6.922489,-72.520389,209.327942,-10851.508789,NaN,5413.219727,6877.872559,NaN,252.085007,...,4.745094,NaN,3827.719971,3460.020020,NaN,2.0,3.0,NaN,5,47
3,579583159167877160,7.741210,-72.323385,NaN,74751.789062,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,0.000000,NaN,NaN,1.0,NaN,1,47
4,579583846362645099,7.790435,-72.232910,NaN,-8035.000977,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,0.000000,NaN,NaN,1.0,NaN,1,47
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
95,628768506166379396,106.306918,-10.671005,-2942.552246,-27179.855469,NaN,4361.677947,24215.727635,NaN,4714.790039,...,34.131329,NaN,2896.330078,27277.400391,NaN,22.0,34.0,NaN,63,Seagull
96,628761840377135727,106.100971,-10.622229,-494.534424,-12141.134766,NaN,1499.251924,10298.447894,NaN,359.585999,...,11.110450,NaN,896.500977,3222.449951,NaN,9.0,33.0,NaN,42,Seagull
97,628761840377135283,106.051326,-10.565356,NaN,535.958740,NaN,NaN,2931.216734,NaN,NaN,...,6.435827,NaN,NaN,851.658020,NaN,NaN,7.0,NaN,13,Seagull
98,630406022577525294,106.155788,-10.406509,NaN,-2419.784668,NaN,NaN,999.806189,NaN,NaN,...,1.865190,NaN,NaN,486.170990,NaN,NaN,12.0,NaN,15,Seagull
99,628769055922194180,106.613341,-10.500749,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2,Seagull

In [93]:
matched_diaObjects_lpv['Region'].value_counts()

Region
Fornax     45
47         33
Seagull    21
LGLF        1
Name: count, dtype: int64

**Adding labels and combining into one dataframe**

In [94]:
#Add labels to each dataframe
matched_diaObjects_rrl['Class'] = 'RR Lyrae'
matched_diaObjects_ceph['Class'] = 'Cepheid'
matched_diaObjects_lpv['Class'] = 'Long Period Variable'

#Combine dataframes (with new labels) into one dataframe
labeled_table = pd.concat([matched_diaObjects_rrl, matched_diaObjects_ceph, matched_diaObjects_lpv], axis=0, ignore_index=False)

In [95]:
labeled_table

,diaObjectId,ra,dec,g_psfFluxMean,r_psfFluxMean,i_psfFluxMean,g_psfFluxSigma,r_psfFluxSigma,i_psfFluxSigma,g_psfFluxChi2,...,i_psfFluxStetsonJ,g_psfFluxMAD,r_psfFluxMAD,i_psfFluxMAD,g_psfFluxNdata,r_psfFluxNdata,i_psfFluxNdata,nDiaSources,Region,Class
0,579583227887354659,7.277627,-72.453601,NaN,6659.355957,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,0.000000,NaN,NaN,1.0,NaN,1,47,RR Lyrae
1,579574706672238627,4.974821,-72.683373,2142.085449,NaN,NaN,NaN,NaN,NaN,0.000000e+00,...,NaN,0.000000,NaN,NaN,1.0,NaN,NaN,1,47,RR Lyrae
2,579574569233285135,6.011728,-72.654608,-2534.255615,NaN,-7.695698,NaN,NaN,7380.872768,5.176740e-13,...,15.224242,0.000000,NaN,5219.069824,1.0,NaN,2.0,3,47,RR Lyrae
3,579575187708576418,6.298868,-72.611684,7049.521484,NaN,2416.182129,NaN,NaN,NaN,0.000000e+00,...,NaN,0.000000,NaN,0.000000,1.0,NaN,1.0,2,47,RR Lyrae
4,579575256428052817,5.980350,-72.590526,2554.464600,-6780.240234,-801.362061,NaN,2091.403995,5294.444401,0.000000e+00,...,12.702006,0.000000,1478.849976,4499.990234,1.0,2.0,4.0,7,47,RR Lyrae
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
95,628768506166379396,106.306918,-10.671005,-2942.552246,-27179.855469,NaN,4361.677947,24215.727635,NaN,4.714790e+03,...,NaN,2896.330078,27277.400391,NaN,22.0,34.0,NaN,63,Seagull,Long Period Variable
96,628761840377135727,106.100971,-10.622229,-494.534424,-12141.134766,NaN,1499.251924,10298.447894,NaN,3.595860e+02,...,NaN,896.500977,3222.449951,NaN,9.0,33.0,NaN,42,Seagull,Long Period Variable
97,628761840377135283,106.051326,-10.565356,NaN,535.958740,NaN,NaN,2931.216734,NaN,NaN,...,NaN,NaN,851.658020,NaN,NaN,7.0,NaN,13,Seagull,Long Period Variable
98,630406022577525294,106.155788,-10.406509,NaN,-2419.784668,NaN,NaN,999.806189,NaN,NaN,...,NaN,NaN,486.170990,NaN,NaN,12.0,NaN,15,Seagull,Long Period Variable
99,628769055922194180,106.613341,-10.500749,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2,Seagull,Long Period Variable

**Store as a csv file**

In [96]:
labeled_table.to_csv('gaiadata_dp1.csv', index=False)